#ifndef IRRIGATION_H_
#define IRRIGATION_H_

#define EXPANDEDIO_DIRA   0x4000
#define EXPANDEDIO_IOA 0x1CFF
#define EXPANDEDIO_WRITE_PORTA 0x4012
#define EXPANDEDIO_RELAY_ENABLE  0x0040
#define EXPANDEDIO_IRRIGATION_ENABLE  0x0240
#define EXPANDEDIO_IRRIGATION_ENABLE_BIT 0x0200
#define EXPANDEDIO_RELAY_DISABLE  0x0140
#define EXPANDEDIO_IRRIGATION_DISABLE  0x0040
#define EXPANDEDIO_CUTTER_DISABLED   0x4040
#define EXPANDEDIO_CUTTER_ENABLED    0x0040
#define EXPANDEDIO_WD_CLEAR  0x8040
#define EXPANDEDIO_PORTA 0x00

#define EXPANDEDIO_DIRB   0x4001
#define EXPANDEDIO_IOB 0x0FFF
#define EXPANDEDIO_WRITE_PORTB 0x4013
#define EXPANDEDIO_RELEASE_HANDPIECE 0x0000
#define EXPANDEDIO_HOLD_HANDPIECE 0x8000
#define EXPANDEDIO_CUTTER_FAULT 0x0000
#define EXPANDEDIO_CUTTER_FAULT_CLEAR 0x4000
#define EXPANDEDIO_PORTB 0x01

#define EXPANDEDIO_CS_DELAY 150

extern int g_ulIrrigationCurrent;
extern int g_ulIrrigationLevel;

int IrrInit(void);
int IrrSetLevel(int);
int IrrGetLevel(int);
int IrrReadCurrent(void);
int IrrSetCurrentLevel(int);
void ExpandedIOUpdate(int,unsigned int);

#endif /*IRRIGATION_H_*/
